### ISSUE TITLE
Erro 302

### ISSUE THREAD

**Issue by brunocs86** [dancodeweb/crudphp#1]
Boa noite,

Amigo tenho tentando rodar o seu projeto utilizando o comando php -S localhost:80, porém tem dado o erro 302, você teria como me auxliar?

No mais muito obrigado

**Comment by ribafs** [comment]
Rodei agora mas em um diretório do apache e funcionou. Apenas não reconhece login e senha.

**Comment by dancodeweb** [comment]
Nossa, GIT fail! @brunocs86 , nunca recebi notificação desta issue. Lamento muito nunca ter respondido. Realmente a forma como o projeto foi contstruído (principalmente conexão htaccess e rotas) não funciona corretamente usando a função de localhost do PHP. Em servidores virtuais comuns (Apache, Nginx, LAMP, XAMPP) ele vai funcionar corretamente.

**Comment by ribafs** [comment]
Quando usamos o comando
php -S localhost:8080
Ele cria um ambiente de virtualhost, como se a aplicação estivesse sozinha no raiz web /, já no documentroot do Apache geralmente criamos um diretório para ela /dirapp.

**Comment by dancodeweb** [comment]
Fechando a issue.

**Comment by brunocs86** [comment]
> Nossa, GIT fail! @brunocs86 , nunca recebi notificação desta issue. Lamento muito nunca ter respondido. Realmente a forma como o projeto foi contstruído (principalmente conexão htaccess e rotas) não funciona corretamente usando a função de localhost do PHP. Em servidores virtuais comuns (Apache, Nginx, LAMP, XAMPP) ele vai funcionar corretamente.

Obrigado pela resposta!
